name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v1

      - name: Env
        run: |
          # ACTIONS_RUNTIME_TOKEN, ACTIONS_RUNTIME_URL should be exposed
          env|sort

      - uses: actions/checkout@v3

      - run: |
          docker buildx build \
            --cache-from=type=gha \
            --cache-to=type=gha,mode=max \
            --tag test \
            .
