name: Deno

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  worker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [37, 42]
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - run: deno run main.ts ${{ matrix.version }}

  gather:
    name: Gather worker outputs
    needs: worker
    runs-on: ubuntu-latest
    steps:
      - run: echo ok
