name: Test Github Bun Script

on:
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: homburg/github-bun-script@main
        with:
          script: |
            console.log("Hello!");
