name: Test Github Bun Script

on:
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: homburg/github-bun-script@main
        with:
          script: |
            import { $ } from "bun";

            const { stdout, stderr, exitCode } = await $`echo "Hello World!"`.quiet();

            console.log(stdout); // Buffer(6) [ 72, 101, 108, 108, 111, 32 ]
            console.log(stderr); // Buffer(0) []
            console.log(exitCode); // 0
