name: "Block PR by label: block-pr"
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:

  check_labels:
    name: "Require label not present: block-pr"
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        id: label_check
        continue-on-error: true
        with:
          one_of: block-pr
          repo_token: ${{ secrets.PAT }}
          allow_failure: true
        
      - name: Block PR if label is present
        uses: actions/github-script@v6
        with:
          script: |
            const label_check_output = ${{ toJSON(steps.label_check.outputs.label_check) }};

            core.summary
              .addHeading('Label checker output')
              .addRaw(`\n\`\`\`json\n${JSON.stringify(label_check_output, null, 2)}\n\`\`\`\n`)
              .write()

            if (label_check_output.one_of_labels_present) {
              core.setFailed('PR blocked by label: block-pr');
            }
