name: Test tailscale github action

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tailscale:
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

  otel-export-trace:
    if: always()
    name: OpenTelemetry Export Trace
    runs-on: ubuntu-latest
    needs: [tailscale] # must run when all jobs are complete
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Export Workflow Trace
        uses: inception-health/otel-export-trace-action@latest
        with:
          otlpEndpoint: ${{ secrets.COROOT_OTLP_ENDPOINT }}
          otlpHeaders: ${{ secrets.COROOT_OTLP_HEADERS }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
