name: Test Octo STS

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test-octo-sts:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed to federate tokens.

    steps:
    - uses: octo-sts/action@210248e8ae1ae1550aa6e232c6f192b3ccbf7335
      id: octo-sts
      with:
        scope: homburg/build-repo
        identity: push

    - env:
        GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
      run: |
        gh repo list